Repository jordy1611/Stretch-Auth, pull requests merged in 2020-09, with the labels that each got.

#1 js-Intialization
  stretch-auth/database.rules.json
  stretch-auth/package-lock.json
  stretch-auth/package.json
  stretch-auth/public/index.html
  stretch-auth/src/App.js
  stretch-auth/src/App/App.css
  stretch-auth/src/App/App.js
  stretch-auth/src/App/App.test.js
  stretch-auth/src/CardContainer/CardContainer.css
  stretch-auth/src/CardContainer/CardContainer.js
  stretch-auth/src/CardContainer/CardContainer.test.js
  stretch-auth/src/FormContainer/FormContainer.css
  stretch-auth/src/FormContainer/FormContainer.js
  stretch-auth/src/FormContainer/FormContainer.test.js
  stretch-auth/src/Header/Header.css
  stretch-auth/src/Header/Header.js
  stretch-auth/src/Header/Header.test.js
  stretch-auth/src/Login/Login.css
  stretch-auth/src/Login/Login.js
  stretch-auth/src/Login/Login.test.js
  stretch-auth/src/PokeCard/PokeCard.css
  stretch-auth/src/PokeCard/PokeCard.js
  stretch-auth/src/PokeCard/PokeCard.test.js
  stretch-auth/src/PokeForm/PokeForm.css
  stretch-auth/src/PokeForm/PokeForm.js
  stretch-auth/src/PokeForm/PokeForm.test.js
  stretch-auth/src/index.js
Labels: enhancement

#11 Firebase struggles
  stretch-auth/apiKey.js
  stretch-auth/package-lock.json
  stretch-auth/package.json
  stretch-auth/public/index.html
  stretch-auth/src/App/App.js
  stretch-auth/src/index.js
Labels: Oauth, firebase

#12 Bm/feature/api data
  stretch-auth/src/App/App.js
  stretch-auth/src/CardContainer/CardContainer.js
  stretch-auth/src/PokeCard/PokeCard.js
Labels: API, React, enhancement

#13 Js initial page layouts
  stretch-auth/package-lock.json
  stretch-auth/src/App/App.css
  stretch-auth/src/App/App.js
  stretch-auth/src/CardContainer/CardContainer.css
  stretch-auth/src/CardContainer/CardContainer.js
  stretch-auth/src/FormContainer/FormContainer.css
  stretch-auth/src/FormContainer/FormContainer.js
  stretch-auth/src/Header/Header.css
  stretch-auth/src/Header/Header.js
  stretch-auth/src/Login/Login.js
  stretch-auth/src/PokeCard/PokeCard.css
  stretch-auth/src/PokeForm/PokeForm.css
  stretch-auth/src/PokeForm/PokeForm.js
  stretch-auth/src/sampleData/fin.jpeg
Labels: enhancement, styling

#14 Feature/display login
  stretch-auth/.gitignore
  stretch-auth/fire.js
  stretch-auth/src/App/App.js
  stretch-auth/src/Login/Login.js
  stretch-auth/src/secrets.json
Labels: Oauth, enhancement, firebase

#15 Fix typos so that page renders properly
  stretch-auth/src/App/App.js
  stretch-auth/src/CardContainer/CardContainer.js
Labels: bugfix

#16 Feature/user info
  package-lock.json
  stretch-auth/package-lock.json
  stretch-auth/package.json
  stretch-auth/src/App/App.js
  stretch-auth/src/Header/Header.js
  stretch-auth/src/Login/Login.js
Labels: Oauth, enhancement, firebase

#17 Bm/prop functionality
  stretch-auth/src/App/App.js
  stretch-auth/src/FormContainer/FormContainer.js
  stretch-auth/src/PokeForm/PokeForm.js
Labels: React, enhancement

#18 Js styling
  README.md
  stretch-auth/src/App/App.css
  stretch-auth/src/FormContainer/FormContainer.css
  stretch-auth/src/Header/Header.css
  stretch-auth/src/Header/Header.js
  stretch-auth/src/PokeForm/PokeForm.css
  stretch-auth/src/PokeForm/PokeForm.js
  stretch-auth/src/assets/charIcon.png
  stretch-auth/src/assets/pikaIcon.png
  stretch-auth/src/assets/pokeball.png
  stretch-auth/src/index.css
  stretch-auth/src/sampleData/fin.jpeg
Labels: styling

#19 Feature/user info
  stretch-auth/src/App/App.js
  stretch-auth/src/Header/Header.js
  stretch-auth/src/Login/Login.js
Labels: Oauth, React, enhancement, firebase

#20 Js/catch pokemon styling
  stretch-auth/src/FormContainer/FormContainer.css
  stretch-auth/src/FormContainer/FormContainer.js
Labels: styling

#21 Remove additional login button, once user logged in they are now redi…
  stretch-auth/src/Header/Header.js
  stretch-auth/src/Login/Login.js
Labels: enhancement

#29 Feature/display user info
  stretch-auth/src/App/App.js
  stretch-auth/src/Header/Header.css
  stretch-auth/src/Header/Header.js
Labels: enhancement, styling

#22 Fix bug with missing sprites and rename variable bulbasaur to be more…
  stretch-auth/src/App/App.js
  stretch-auth/src/CardContainer/CardContainer.js
  stretch-auth/src/PokeCard/PokeCard.js
Labels: API, React, bugfix

#23 Js loading page styling
  README.md
  stretch-auth/src/App/App.css
  stretch-auth/src/App/App.js
  stretch-auth/src/FormContainer/FormContainer.css
  stretch-auth/src/assets/bulbaIcon.png
  stretch-auth/src/assets/catcherIcon.png
  stretch-auth/src/assets/squirtleIcon.png
Labels: enhancement, styling

#30 Js remove pokemon from team
  stretch-auth/src/App/App.js
  stretch-auth/src/FormContainer/FormContainer.js
Labels: React, enhancement

#31 Bm/feature/local storage pulls
  stretch-auth/src/App/App.js
  stretch-auth/src/CardContainer/CardContainer.js
  stretch-auth/src/FormContainer/FormContainer.js
Labels: React, enhancement

#32 Feature/header tests
  stretch-auth/package-lock.json
  stretch-auth/package.json
  stretch-auth/src/App/App.js
  stretch-auth/src/Header/Header.js
  stretch-auth/src/Header/Header.test.js
Labels: Testing

#33 Js pokecard display & overall styling
  stretch-auth/src/App/App.js
  stretch-auth/src/CardContainer/CardContainer.css
  stretch-auth/src/CardContainer/CardContainer.js
  stretch-auth/src/FormContainer/FormContainer.js
  stretch-auth/src/Header/Header.css
  stretch-auth/src/Header/Header.js
  stretch-auth/src/PokeCard/PokeCard.css
  stretch-auth/src/PokeCard/PokeCard.js
  stretch-auth/src/PokeForm/PokeForm.js
Labels: React, styling

#34 Js create test data
  stretch-auth/src/App/App.js
  stretch-auth/src/PokeForm/PokeForm.js
  stretch-auth/src/testData.js
Labels: React, Testing

#36 Bm/feature/proptypes
  stretch-auth/package.json
  stretch-auth/src/App/App.js
  stretch-auth/src/CardContainer/CardContainer.js
  stretch-auth/src/FormContainer/FormContainer.js
  stretch-auth/src/Header/Header.js
  stretch-auth/src/Login/Login.js
  stretch-auth/src/PokeCard/PokeCard.js
  stretch-auth/src/PokeForm/PokeForm.js
Labels: documentation, enhancement

#37 Js form page testing
  stretch-auth/package-lock.json
  stretch-auth/package.json
  stretch-auth/src/FormContainer/FormContainer.test.js
  stretch-auth/src/PokeForm/PokeForm.js
  stretch-auth/src/PokeForm/PokeForm.test.js
  stretch-auth/src/testData.js
Labels: React, Testing

#38 Bm/feature/error message
  stretch-auth/src/App/App.js
  stretch-auth/src/CardContainer/CardContainer.test.js
  stretch-auth/src/FormContainer/FormContainer.css
  stretch-auth/src/FormContainer/FormContainer.js
  stretch-auth/src/Header/Header.js
  stretch-auth/src/PokeCard/PokeCard.js
  stretch-auth/src/PokeCard/PokeCard.test.js
Labels: Oauth, React, Testing, bugfix, documentation, enhancement

#39 Feature/testing
  stretch-auth/src/App/App.js
  stretch-auth/src/App/App.test.js
  stretch-auth/src/Header/Header.test.js
  stretch-auth/src/apiCalls.js
  stretch-auth/src/testData.js
Labels: Testing

#40 Remove console logs and comments
  stretch-auth/public/index.html
  stretch-auth/public/manifest.json
  stretch-auth/src/App/App.test.js
  stretch-auth/src/FormContainer/FormContainer.css
  stretch-auth/src/FormContainer/FormContainer.js
  stretch-auth/src/FormContainer/FormContainer.test.js
  stretch-auth/src/Header/Header.css
  stretch-auth/src/PokeCard/PokeCard.css
  stretch-auth/src/index.js
Labels: enhancement
